version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'

volumes:
  postgres_data: