version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./worker-entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - web
      - cache

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'


volumes:
  postgres_data: